# ==========================================================================
# ProPhysics - Master Orchestrator Build Script
# File: Makefile.nmake (Root-Verzeichnis)
# Architecture: Sequential Product-Line Compilation & Macro Overriding
# ==========================================================================

MAKE = nmake.exe

# Das Standard-Target koordiniert die gesamte Build-Reihenfolge
all: build_all

build_all:
	@echo ==========================================================================
	@echo [MASTER]: Starte industrielle Master-Kompilierung der Pro-Familie...
	@echo ==========================================================================
	@echo [MASTER]: Step 1 -> Baue Standalone UI-Framework (ProDiBatch)...
	@cd ProDiBatch && $(MAKE) /NOLOGO /f Makefile.nmake
	@echo.
	@echo [MASTER]: Step 2 -> Baue Core-Simulation-Engine (ProPhysics)...
	@cd ProPhysics && $(MAKE) /NOLOGO /f Makefile.nmake OUT_DIR=..\bin\ProPhysics PRODIBATCH_BIN=..\bin\ProDiBatch
	@echo.
	@echo [MASTER]: Step 3 -> Baue Haupt-Bootstrapper / Applikation (Observer)...
	@cd Observer && $(MAKE) /NOLOGO /f Makefile.nmake
	@echo ==========================================================================
	@echo [MASTER]: Master-Kompilierung erfolgreich abgeschlossen!
	@echo [MASTER]: Alle Endprodukte steril einsatzbereit unter .\bin\
	@echo ==========================================================================

# Porentiefe Kaskaden-Säuberung: Ruft die Unter-Skripte auf und rasiert den bin-Zweig
clean:
	@echo [MASTER]: Starte kaskadierende Saeuberung des gesamten Projektbaums...
	@if exist ProDiBatch\Makefile.nmake (cd ProDiBatch && $(MAKE) /NOLOGO /f Makefile.nmake clean)
	@if exist ProPhysics\Makefile.nmake (cd ProPhysics && $(MAKE) /NOLOGO /f Makefile.nmake clean)
	@if exist Observer\Makefile.nmake (cd Observer && $(MAKE) /NOLOGO /f Makefile.nmake clean)
	@if exist bin rmdir /S /Q bin
	@echo [MASTER CLEAN]: Projektbaum zu 100% steril bereinigt.